// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type GoodbyeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyeRequest) Reset()         { *m = GoodbyeRequest{} }
func (m *GoodbyeRequest) String() string { return proto.CompactTextString(m) }
func (*GoodbyeRequest) ProtoMessage()    {}
func (*GoodbyeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *GoodbyeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyeRequest.Unmarshal(m, b)
}
func (m *GoodbyeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyeRequest.Marshal(b, m, deterministic)
}
func (m *GoodbyeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyeRequest.Merge(m, src)
}
func (m *GoodbyeRequest) XXX_Size() int {
	return xxx_messageInfo_GoodbyeRequest.Size(m)
}
func (m *GoodbyeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyeRequest proto.InternalMessageInfo

func (m *GoodbyeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GoodbyeResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodbyeResponse) Reset()         { *m = GoodbyeResponse{} }
func (m *GoodbyeResponse) String() string { return proto.CompactTextString(m) }
func (*GoodbyeResponse) ProtoMessage()    {}
func (*GoodbyeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *GoodbyeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodbyeResponse.Unmarshal(m, b)
}
func (m *GoodbyeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodbyeResponse.Marshal(b, m, deterministic)
}
func (m *GoodbyeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodbyeResponse.Merge(m, src)
}
func (m *GoodbyeResponse) XXX_Size() int {
	return xxx_messageInfo_GoodbyeResponse.Size(m)
}
func (m *GoodbyeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodbyeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodbyeResponse proto.InternalMessageInfo

func (m *GoodbyeResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*GoodbyeRequest)(nil), "GoodbyeRequest")
	proto.RegisterType((*GoodbyeResponse)(nil), "GoodbyeResponse")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0xe2, 0xf1, 0x48, 0xcd,
	0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xb4, 0xb9, 0x78, 0xa1, 0x6a,
	0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8, 0x38, 0xc0, 0xa6, 0x64, 0xe6, 0xa5, 0x4b,
	0x30, 0x81, 0x15, 0xc2, 0xf9, 0x4a, 0x2a, 0x5c, 0x7c, 0xee, 0xf9, 0xf9, 0x29, 0x49, 0x95, 0xa9,
	0xf8, 0x8c, 0xd4, 0xe5, 0xe2, 0x87, 0xab, 0x22, 0x6c, 0xa8, 0x51, 0x32, 0x17, 0xbb, 0x3b, 0xc4,
	0xd9, 0x42, 0x1a, 0x5c, 0xac, 0x60, 0xc7, 0x08, 0xf1, 0xea, 0x21, 0x3b, 0x5c, 0x8a, 0x4f, 0x0f,
	0xc5, 0x8d, 0x4a, 0x0c, 0x42, 0x7a, 0x40, 0x4d, 0x10, 0x3b, 0x84, 0xf8, 0xf5, 0x50, 0xdd, 0x24,
	0x25, 0xa0, 0x87, 0x66, 0xbd, 0x12, 0x43, 0x12, 0x1b, 0x38, 0x44, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x73, 0xc6, 0x17, 0x2a, 0x22, 0x01, 0x00, 0x00,
}
